services:
  back:
    build: ./BrazilSurvival.BackEnd
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:5000"
  front:
    build: ./BrazilSurvival.FrontEnd
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:8080"
    depends_on:
      - back